### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by IzzySoft** [tommi1hirvonen/ExifNotes#16]
Would you mind making the APK available by e.g. attaching it to the corresponding [release](https://github.com/tommi1hirvonen/ExifNotes/releases), so folks without access to Google's walled garden can give it a try, too? That's be great, so thanks in advance!

PS: and it would be phantastic if the GMaps dependency could be replaced with OSM then, to make the app entirely F/LOSS. Just a suggestion :wink:

**Comment by AngelaDMerkel** [comment]
Tommi includes the source and you can build it yourself. It is completely FOSS.

**Comment by IzzySoft** [comment]
> you can build it yourself

I'm not a dev and I don't have a build env – so sorry to disappoint, but I can't. And I wasn't asking especially for me, but in general: the group of people preferring to run their devices without Google ties is growing. So if the APK would be available at a place one usually looks for (that is the releases page), that would help; further it would enable me to establish the app in [my F-Droid repo](https://apt.izzysoft.de/fdroid) (due to the GMaps dependency it's not "completely FOSS" and thus does not comply with the F-Droid.org inclusion criteria), which then would make it quite easy for the mentioned "target group" to find, install and keep it updated.

Thanks for the APK, though – but for the process described I'd need it in a place where my updater can fetch new releases automatically :wink:

**Comment by AngelaDMerkel** [comment]
> due to the GMaps dependency it's not "completely FOSS" and thus does not comply with the F-Droid.org inclusion criteria

Thanks for the education on the subject. I wasn't aware. 

> Thanks for the APK, though 

This is a poor solution, really, but I figured it would help as a one time answer. There is a [github action](https://github.com/marketplace/actions/build-android-app) already written that could automate the build process for Tommi. Given that the app is not being built all that often, the [free tier](https://github.com/features/actions) would almost definitely suffice. I am not a contributor, but if Tommi wouldn't mind, I can set up the action.

**Comment by tommi1hirvonen** [comment]
Thanks for the interesting conversation and suggestions! Currently my release workflow is the following:
1. Update the app's version information
2. Push to remote (git)
3. Generate signed APK
4. Test the release build one more time
5. Upload APK to Google Play Developer Console and create a new release
6. Create a new tag/release in GitHub

So basically I am currently already building/generating an APK that I upload to Play Developer Console. This could probably be automated with GitHub actions to some extent, although from what I've read, that only applies to the alfa and beta channels. Automating production releases in Play Developer Console is not possible (again, as far as I'm aware), though that might be a good thing. I could manually attach the generated APK to the release in GitHub, but I'll have to check what the Play Store terms and conditions might have to say about that.

There are some third party services that regularly extract the APKs from Play Store to make them directly available on their websites. At least that used to be a thing.

Replacing Google Maps and the Google Geocode API with OSM might be a large undertaking, but theoretically possible. But for the time being, it's not on the development roadmap.

Thanks @AngelaDMerkel for the links, I'll check out those GitHub actions.

**Comment by AngelaDMerkel** [comment]
I am no expert, but there are github actions which nominally should be able to push your releases to Google Play using your developer API. I have never tried it, but there are some which claim to be able to do as much.

**Comment by IzzySoft** [comment]
@tommi1hirvonen so basically you just needed to add step 7 to upload the APK to Github releases as well. And yes, AFAIK there are some Github actions available for that.

> There are some third party services that regularly extract the APKs from Play Store

They all require a Google account, so they are not really applicable for this case (where one wants to explicitly have NO Google connections/ties).

> Replacing Google Maps and the Google Geocode API with OSM might be a large undertaking, but theoretically possible

Yupp, has been done by several other projects in the past – often in similar context. And when I suggested that I certainly didn't expect you'd ship it the next day :rofl: That's what [my F-Droid repo](https://apt.izzysoft.de/fdroid) is for: apps which are "so close but not yet there". Once OSM is in place instead of GMaps, your app could advance to F-Droid.org if you wish.

So maybe until the proper Github action is in place, could you attach the APK you already have to the latest (and future) release(s)?

**Comment by AngelaDMerkel** [comment]
@tommi1hirvonen I know this is more or less as a hobby project, but if you set up some way to donate please considering putting it in the description.

**Comment by tommi1hirvonen** [comment]
@IzzySoft I've now attached the related APK to the latest release (1.18.3) here in GitHub. It looks like many other open source Android apps are doing the same thing. I'm keeping the APK file name as it is once it's built (app-release.apk) and will continue to follow that convention.

@AngelaDMerkel A surprising number of people have asked about the possibility of donating. I've looked at some alternatives but came to the conclusion some time ago that the costs of such services could easily be more than the donations coming in. Would you happen to have any suggestions? I'd be interested in taking a second look.

**Comment by IzzySoft** [comment]
Thanks @tommi1hirvonen! Your app then will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.tommihirvonen.exifnotes) with the next sync tomorrow at around 7 pm UTC. Updates will be checked for daily around the same time: whenever there's a newer tag following the current naming convention (i.e. `v<versionName>`) and having an APK attached, that will be pulled.

As for donations, if payout via PayPal or Stripe is OK with you, you might wish to take a look at [Liberapay](https://liberapay.com/) (I've used them back when they supported payout via SEPA and that worked pretty well; as I do not use PP/Stripe my account stopped working when that other payment provider dropped them out). Some other service maybe worth looking at you can discover when checking what you can specify with [Github's `FUNDING.yml`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) – and if you use that file, my updater will automatically pick it up along with future releases.
