### ISSUE TITLE
Increment frame number when copying a frame

### ISSUE THREAD

**Issue by classabbyamp** [tommi1hirvonen/ExifNotes#18]
**Is your feature request related to a problem? Please describe.**
When doing data entry for a roll shot in the past or several shots at once, it is easier for me to enter the data once, then copy it. This copy operation keeps the same frame number for each frame, requiring me to manually change the frame number on each duplicate.

**Describe the solution you'd like**
The frame number should increment when copying a frame, e.g. copying frame 4 would give frame 5 with all other data the same

**Describe alternatives you've considered**
Doing it manually

**Comment by tommi1hirvonen** [comment]
There is an existing frame batch edit feature that could be useful here. After you've copied the frames you want to copy (one or multiple), the copied frames remain selected. Then you can click on the edit icon and batch edit the frame numbers of the selected frames. This allows you to increment the frame numbers (either up or down) by some number.

Have you tried using that feature and does it make the process any smoother?

**Comment by classabbyamp** [comment]
I think I tried this but it moved all selected frame numbers the same amount? it's been a bit since I did it

**Comment by mrtorrent** [comment]
+1 on this issue. I often add shots to a roll later on, and copying saves time, but changing the frame number adds back some of the labor. I have never had a situation where I wanted the frame number to stay the same when copying. Is there a use case for that? I can't think of one.
