### ISSUE TITLE
Custom shutter speed values

### ISSUE THREAD

**Issue by tommi1hirvonen** [tommi1hirvonen/ExifNotes#2]
**Current behaviour**

The shutter speed property for frames can now be selected from a list of preset values with different increments.

**New feature**

In the same way as aperture values can be customized, the shutter speed value should be customizable. If the shutter speed used is not included in the list of preset values, the user should be able to manually enter a custom value.

**Why is this useful**

Some cameras might have unconventional shutter speeds (e.g. some Leica cameras), which are not among any of the preset shutter speed values.

**Comment by fotopan** [comment]
That's right, some cameras have additional intermediate shutter speeds, like Pentax LX with 1/75 flash sync speed.
