### ISSUE TITLE
Complementary picture isn't saved

### ISSUE THREAD

**Issue by mogol07** [tommi1hirvonen/ExifNotes#25]
**Describe the bug**
After update to new version complementary pictures are not saved. I could shot (now it's not so comfortable as before), but when I press Ok after shot, it's not saved. 
Old pictures which was made in previous version are present in roll.

**To Reproduce**

**Expected behavior**
Image are attached to record.

**Screenshots**

**Device (please complete the following information):**
 - Poco F2 Pro
 - Android version: 12 (MIUI 13.0.8)
 - App version: 1.18.4

**Additional context**
![Screenshot](https://user-images.githubusercontent.com/25278978/219898645-d57b1d2d-a26a-4ee8-9ae3-9b69ae849137.jpg)

**Comment by tommi1hirvonen** [comment]
I may have been able to reproduce this same bug on my Samsung Galaxy Note 3 running Android L (5). It looks like `FrameEditFragment` can behave differently on different devices. When returning from the camera activity back to `FrameEditFragment`, on some devices only `onResume` is called and on some devices the entire Fragment is recreated. The app currently behaves correctly when only `onResume` is called. If the Fragment is recreated, the complementary picture information is currently lost.

**Comment by tommi1hirvonen** [comment]
I've just released v1.18.5 to the beta channel on Google Play. It should be available shortly if you have signed up for beta testing. Please try if it fixes the bug for you and if not, feel free to reopen this issue.
