### ISSUE TITLE
Issue with Database Import

### ISSUE THREAD

**Issue by BooDoo** [tommi1hirvonen/ExifNotes#47]
**Describe the bug**
Unable to Import Database (Android 14)

**To Reproduce**
1. Go to Settings, press **Export Database** and save to locally or to remote storage.
2. Press **Import Database**, agree to Continue, then navigate to the file exported in Step (1) and select it
4. Receive `Database integrity check failed. The old database will be used.'` error modal.

**Expected behavior**
`Database imported successfully` message

**Device (please complete the following information):**
 - Make & model: Google Pixel 5a
 - Android version: 14
 - App version 1.20.0 **update to add: same behavior in 1.20.1**

**Additional context**
Error occurs on my Pixel 5a running Android 14 (Security update Oct 5 2023)
Expected behavior (successful import) occurs on my Pixel 3a running Android 12 (Security update May 5 2022)

 - Both phones are running ExifNotes v1.20.0
 - Both phones export .db files that open in an external sqlite client
 - Both phones export .db files with identical schema
 - Both phones export .db files that import successfully on Android 12/Pixel 3a (ExifNotes 1.20.0)
 - *Neither `.db` file successfully imports into ExifNotes on Android 14/Pixel 5a (ExifNotes 1.20.0)*
 - *Neither `.db` file successfully imports into ExifNotes on Android 14/Pixel 5a (ExifNotes 1.20.1)*

**Comment by BooDoo** [comment]
I can go through add re-add my bodies/lenses/film stocks in my new version so this isn't the end of the world (all my actual shots I'd already exported in CSV etc) but I did want to report the bug in case it impacts others or indicative of a larger problem.

Thanks for the app I really do appreciate the work you've done with it!

**Comment by tommi1hirvonen** [comment]
I think I've found the cause of this issue. Android 14 for some reason reports the SQLite database column datatypes in uppercase (at least for some columns) whereas previously they have been lowercase. Luckily letter casing is completely irrelevant for db datatypes, so we can just ignore it. Currently working on a fix.

**Comment by BooDoo** [comment]
Thanks so much for the fix! I've been using the app for 2 years now (82 rolls) and looking forward to another in 2024 💜

**Comment by antondd** [comment]
Fix works, thanks!
