### ISSUE TITLE
Take new complementary picture: Move out of Options

### ISSUE THREAD

**Issue by Rex176** [tommi1hirvonen/ExifNotes#55]
ExifNotes would be even more streamlined to use if "Take new complementary picture" were on the main screen of "Add new frame" instead of having to choose from "Options". 

How about two buttons at the bottom of the screen: a camera for when you want to take a new picture and an image icon for when you want to select from gallery. You can then get rid of "... Options".

**Comment by tommi1hirvonen** [comment]
Thanks for the suggestion @Rex176 ! This improvement will be included in the next Jetpack Compose based release of Exif Notes, which is a complete rewrite of the UI layer. I hope to release it before the end of 2024.
