### ISSUE TITLE
Select All and then Editing does not work properly

### ISSUE THREAD

**Issue by Nesaijn** [tommi1hirvonen/ExifNotes#56]
**Describe the bug**
In the view with the list of frames of an roll you can select a single frame with a long press. Then the option to select all frames in the roll appears at the top bar (the one left to the trash can). When pressing it all frames are being selected but when selecting to edit them afterwards only the first manually selected frame is considered for the edit.

**To Reproduce**
1. Got a roles view.
2. Select a role with multiple frames, entering the view with all the frames in the role.
3. Long press a frame to select it.
4. Select to select all frames in the roles with the newly appeared icon left to the trash can at the top bar.
5. Select to edit the frames with the pencil symbol at the top bar

**Expected behavior**
I expect all the selected frames to be edited instead of only the first manually selected one.

**Screenshots**

**Device (please complete the following information):**
 - Make & model: Google Pixel 6a
 - Android version: 14
 - App version 1.21.0

**Additional context**
When selected them all manually it works as expected.

EDIT: Add "Additional context"

**Comment by ayykamp** [comment]
Can confirm this is an issue.

**Comment by tommi1hirvonen** [comment]
Thanks for the bug report! A fix for this will be included in the next Jetpack Compose based release of Exif Notes, which is a complete rewrite of the UI layer. I hope to release it before the end of 2024, preferably very soon.

I did a quick test to confirm that, and this issue doesn't appear with the current dev version. For that reason, I'll close this issue as fixed.
