### ISSUE TITLE
Create issue template to facilitate reporting

### ISSUE THREAD

**Issue by mrtorrent** [tommi1hirvonen/ExifNotes#9]
It would be helpful and encourage good issue reporting to create a template that is auto-populated when creating a new issue in GitHub. See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by tommi1hirvonen** [comment]
Thanks for the suggestion! I'm not sure why I hadn't included issue templates before since they definitely help in creating new issues, especially for newcomers. I've added templates for bug reports and feature requests in 29f02a8e9b5872221917da44953e6e2e3b8e1f8d.
